### ISSUE TITLE
A version of memoised function which has forgetful nature

### ISSUE THREAD

**Issue by Mullefa** [hadley/memoise#11]
I am memoising a function in a shiny application to limit calls to a database. However, I want it to reset its cache at the start of each new day. This is the solution I've come up with:

```R
forget_using <- function(f, value) {
  v <- value()
  mem_f <- memoise::memoise(f)

  function(...) {
    v_ <- value()
    if (v != v_) {
      memoise::forget(mem_f)
      v <<- v_
    }
    mem_f(...)
  }
}

# example use case
mem_run_query <- forget_using(run_query, Sys.Date)
```

If you think something like this sits in the package let me know, and I'll do a pull request. In that event, I think a better name is probably needed.

**Comment by jimhester** [comment]
This is now supported with the following syntax.

```r
mem_run_query <- memoise(run_query, ~Sys.Date())
```

If you want it to be a 24 hour period (rather than changing at 00:01) you can do the following. _N.B._ `86400 == 60 * 60 * 24`
```r
mem_run_query <- memoise(run_query, 
~{
  current <- as.numeric(Sys.time())
  (current - current %% 86400) %/% 86400
})
```
