### ISSUE TITLE
Memoise with plot

### ISSUE THREAD

**Issue by csgillespie** [hadley/memoise#20]
I suspect this is the same issue as #19 

```
p = memoise(plot)
p(1:10) # Bad
p(1:10, 1:10) #Good
```
Also, I'm thinking that this could be useful in a shiny application (wrapped around a plot call). Is this a sensible thought?

**Comment by jimhester** [comment]
This now no longer errors, but plots are really side effects rather than values, so memoise isn't going to draw to the screen again.
