### ISSUE TITLE
Memoise with data.table

### ISSUE THREAD

**Issue by geneorama** [hadley/memoise#21]
I found an interesting issue that could cause some serious mischief.

Because of the way `data.table` and `memoise` use environments, if you use memoise within a `data.table`'s group by feature you can get an error where the wrong input / output pair get matched.

``` R
library(data.table)
library(memoise)

fib <- function(x) if(x<2) x else fib(x - 2) + fib(x - 1)
fib <- memoise(fib)

dat <- data.table(x=as.numeric(1:10))
dat[ , y := fib(x), x]
dat

fib(1)  ## This returns the largest value for x
```

![image](https://cloud.githubusercontent.com/assets/1392068/13788566/410a9ab2-eaae-11e5-939a-b524a31f4c39.png)

I don't know that I would call this an error or a bug in `memoise` or `data.table`, but it's good to know.

**Comment by hadley** [comment]
You can't expect to use memoise with data.table because data.table functions are not pure (i.e. they change state elsewhere).
