### ISSUE TITLE
Allow additional cache types

### ISSUE THREAD

**Issue by danielecook** [hadley/memoise#24]
I'd be interested in writing my own cache that stores/retrieves items in google datastore, dropbox, AWS, or elsewhere in a decentralized manner. Any thoughts/ideas something like that? I'm working on a google datastore one right now.

Perhaps you could allow custom caches to be provided as an argument for the `memoize` function with the expectation that they'll provide functions for `reset`, `set`, `get`, `has_key`, and `keys`?

**Comment by danielecook** [comment]
[Here](https://github.com/danielecook/memoise) is an example of how memoise could be altered to allow custom cache types. In this case, I'm using google datastore, and it can be used as follows:

```r
key <- "<google cloud oauth key>"
secret <- "<google cloud oauth secret>"
authenticate_datastore(key, secret, "<project-id>")

mem_fib <- memoise(fib, cache = datastore_cache("custom_cache_name"))
mem_fib(20) # Saved to datastore; Can be retrieved on another computer.
mem_fib(20) # Cached version retrieved from google datastore.
```

Using datastore allows a cache to be used across a cluster or between home/work. It's also persistent across sessions. 

But there are some drawbacks. There is an upper limit on the size allowable, and it is obviously slower than using a built-in cache. It's also difficult to clear caches using google datastore, because they don't offer an easy way to delete all items of a certain 'kind,' which in this case are a set of items we classify as being an r cache. However, you can easily setup multiple caches and move between them.

**Comment by jimhester** [comment]
I think this seems like a useful feature thanks! I opened #25 to discuss it further.

**Comment by danielecook** [comment]
I get the following when trying to build:

```
Error in unloadNamespace(pkg_name) : 
  namespace ‘memoise’ is imported by ‘devtools’ so cannot be unloaded
```

Any idea how to get around that?

**Comment by jimhester** [comment]
This will force it to be unloaded.
```r
library(devtools)
unload(inst("memoise"))
```

Alternatively you can use `devtools::load_all()` for development, which will do that for you.

**Comment by tomliptrot** [comment]
Might it be possible to make a redis based cache? This would have the advantage of being persistent and available outside of the R session (to other users etc)

**Comment by jimhester** [comment]
@tomliptrot I am happy to merge a PR of a redis backend if you send one.

Externally backed caching is now functional as of b3b9ae66f5798c6d6ac861e77ff17d515588dd72

**Comment by wlandau-lilly** [comment]
I would also mention DBI here. [storr](https://github.com/richfitz/storr) (and [redux](https://github.com/richfitz/redux)) by @richfitz could cover DBI, redis, and a different kind of file system cache.
