### ISSUE TITLE
Education on MIT license

### ISSUE THREAD

**Issue by levithatcher** [hadley/memoise#26]
It looks like memoise relies on the digest package (which is GPL-2). How does memoise not inherit GPL-2 from digest? Thanks for any education!

EDIT: have now posted this here: http://opensource.stackexchange.com/q/4414/6032 Thanks!

**Comment by jimhester** [comment]
Users actually acquire R dependencies separately (via `install.packages()`) and integrate them on their own, we do not distribute the package as a whole. So each package can be licensed independently of its dependencies.
