### ISSUE TITLE
prevent filesystem indexing for caches?

### ISSUE THREAD

**Issue by davharris** [hadley/memoise#30]
I apologize if this is out of scope, but I noticed that several independent processes on my Mac have started devoting a lot of resources to indexing my cache directories (Spotlight, Time Machine, my online backup service, and [if the caches were in my working directory] RStudio ). 

I'd imagine that Windows and Linux users could have similar problems.  

I'm not sure whether there's anything you can do about these from inside your package, but I wanted to put it on your radar just in case.  Also, it might be worth pointing out in the documentation that users might want to keep their caches in a folder that has these services turned off.

**Comment by jimhester** [comment]
One way to prevent spotlight and time machine indexing is to but the cache in a hidden folder prefixed by `.`. The same will prevent indexing on Windows and Linux.

**Comment by davharris** [comment]
Brilliant. Thanks again!
