### ISSUE TITLE
feature request: improve caching of large objects

### ISSUE THREAD

**Issue by archenemies** [hadley/memoise#31]
When a function is being called with the same object, as opposed to an object which is equal but located somewhere else in memory, there should be a way to avoid the calculation of the checksum or hash. I don't know how to do it, but I have some immutable 100MB objects and it seems like I'm mostly waiting for a checksum to be calculated.

I don't know if the semantics of weak references in R allows us to ensure that a weakly-referenced object has not been modified, but if so then this could be turned into a solution for making Memoise fast for large objects too.

**Comment by jimhester** [comment]
You just need to use a faster hashing algorithm, the default (sha512) is fairly slow.

[xxhash64](https://github.com/Cyan4973/xxHash)  is very fast, it can hash the uncompressed human genome (~ 3GB in size) in less than 1.5 seconds.

``` r
file.size('~/hg38.fa')
#> [1] 3273481150
system.time(digest::digest(algo = "sha512", file = '~/hg38.fa'))
#>    user  system elapsed 
#>  12.540   0.856  13.429
system.time(digest::digest(algo = "xxhash64", file = '~/hg38.fa'))
#>    user  system elapsed 
#>   0.556   0.777   1.339
```

You can use a different hashing algorithm in devel memoise easily.
```r
# devtools::install_github("hadley/memoise")
memoise::memoise(f, cache = cache_memory(algo = "xxhash64"))
```

**Comment by archenemies** [comment]
Thanks for the suggestion.

I tried CRC32 but it sounds like xxhash64 is faster.

Of course, implementing my suggestion would make things even faster - but perhaps it is not worthwhile.

**Comment by archenemies** [comment]
I get that `xxhash64` takes about 75-80% of the CPU time of `crc32`.

Another useful feature might be the ability to make "digest" into a generic function, for instance then one could add a new class implementing an "immutable" wrapper for objects, which computes their digest on demand and caches it. Or a "filename" class which computes the hash of a file's contents, rather than the hash of a string naming the file.

Hashing 3 GB in 1.5 seconds sounds pretty fast, but if 1.5 microseconds is achievable ... then it doesn't sound so fast...

**Comment by jimhester** [comment]
If these features are of interest to you I would suggest working on them and submitting a pull request.

**Comment by archenemies** [comment]
Thanks for the offer. I hope I haven't wasted your time by making these suggestions, but it seems unlikely that I myself would be able to work on them. Cheers.
