### ISSUE TITLE
Question / Request: timeout time as variable not working when variable removed

### ISSUE THREAD

**Issue by fabiangehring** [hadley/memoise#34]
Hi,

When memoising a function like this everything is fine:
```
f <- function(x) {Sys.sleep(2); x}
f <- memoise(f, seconds = ~memoise::timeout(500))
f(1)
f(1)
```

But when passing the timeout time as variable the varaible seems to be evaluated with every function call and throws an error.
```
f <- function(x) {Sys.sleep(2); x}
cacheTime <- 500
f <- memoise(f, seconds = ~memoise::timeout(cacheTime))
rm(cacheTime)
f(1)
f(1)
```

Is there an easy workaround for this?

**Comment by jimhester** [comment]
Capture the timeout before using it in the memoise call.
``` r
f <- function(x) {Sys.sleep(2); x}
cacheTime <- 500
seconds <- memoise::timeout(cacheTime)
f <- memoise::memoise(f, seconds = ~ seconds)
rm(cacheTime)
f(1)
#> [1] 1
f(1)
#> [1] 1
```

**Comment by fabiangehring** [comment]
@jimhester Thx, but this just replaces the problem, when the varibale seconds is deleted. Let me explain my problem a bit more in detail. I'd like to memoise already existing functions in another environment. Probably I could add the variable "cacheTime" to that environment, but I'd like to avoid that and expected it to be "part of the memoised function" once initiated. A dependency during runtime makes it a bit more difficult and it's not the way "normal" R-functions work?

**Comment by jimhester** [comment]
I can't help you further without a concrete example of what you are trying to do, but as far as I can tell this is working as designed.
