### ISSUE TITLE
performance decrease

### ISSUE THREAD

**Issue by eferara** [hadley/memoise#35]
I have noticed a performance decrease between version 1.0.0 from cran and 1.0.0.9001 from github using R 3.3.2 (2016-10-31)

In this example, the median time of the memoised function doubled.

```
x= data.frame(x=1:100000, y=1:100000)
f <- function (i) { x[x[,1]==i,2] }
f2  = memoise::memoise(f)
microbenchmark::microbenchmark( f(50), f2(50) )

# mran ‘1.0.0’
Unit: microseconds
expr     min       lq       mean   median      uq      max neval
f(50)  681.561 741.7170 1020.15498 840.9110 856.430 4976.026   100
f2(50)  71.997  75.3565   92.76033  84.4765  88.796  969.864   100

# github ‘1.0.0.9001’
microbenchmark::microbenchmark( f(50), f2(50) )
Unit: microseconds
expr     min       lq      mean  median        uq      max neval
f(50)  799.953 813.8725 1038.1763 834.031 1372.7195 1878.610   100
f2(50) 151.352 158.7115  170.9893 166.391  175.9905  263.345   100
```

**Comment by jimhester** [comment]
The CRAN version evaluates all arguments, even if they were not explicitly used, which causes issues when functions use `missing()` for example #19.

The current master uses `match.call()` to only evaluate default arguments and those actually used in the call, which has additional runtime overhead, but deals with the `missing()` case correctly.

I removed one statement that is no longer required (https://github.com/hadley/memoise/commit/1b75a6f989ca13302795887424f85176e7f4a391) and should improve performance a little, but there isn't anything that can be done in general.
