### ISSUE TITLE
parameter-less functions memoised with cache_filesystem  get corrupted

### ISSUE THREAD

**Issue by misamae** [hadley/memoise#38]
I have the following two parameter less function memoised. 

`
library(memoise)
f2 <- function() { 2 }
f3 <- function() { 3 }
fc <- cache_filesystem("./TEMP")

cachedf2 <- memoise(f2, cache = fc)
cachedf3 <- memoise(f3, cache = fc)
`
Then running the following two statements generate the same results:

`
> cachedf2()
[1] 2
> cachedf3()
[1] 2
> 
`

Checking the cache files in ./TEMP directory there is only one file generated for both caches. I guess the key in the cache does not take the function name into account. In that case I assume the same issue might happen for functions containing same parameter lists.

**Comment by jimhester** [comment]
Yes you are right, the hash needs to hash the function definition as well as the arguments. Shuold now be fixed.

**Comment by misamae** [comment]
@jimhester I tested the latest version and it is fixed
