### ISSUE TITLE
Name clashes between arguments and memoising procedure

### ISSUE THREAD

**Issue by egnha** [hadley/memoise#43]
**The problem**: Argument names of a memoised function (say, `f`) can be hijacked by names in the body or enclosing environment of the memoising function (`memoise(f)`).

Example:
```R
memoise(function(hash) hash)("Am I OK?")
#> [1] "9ec45ba0998d8bc3150c..." (output truncated)
```
This is not a problem that is likely to be encountered for exotic names, like `` `_f` ``. For ordinary syntactic names, like `hash` or `args`, the likelihood of a name clash is still very low, but not zero. Nevertheless, it might be worthwhile to reduce this likelihood to zero, as this seems possible with a few small changes to `memoise()` (and, accordingly, `has_cache()`).

**A solution**:
1. To fix clashes with names in the enclosing environment — invoke such names by explicit reference to bindings in the enclosing environment.
2. To fix clashes with names assigned in the memoised function body — call the underlying (non-memoised) function `f` in the calling environment, rather than in the function's execution environment, as currently done.

Implementing 1) amounts to changing `` `_f` `` to `` encl$`_f` ``, etc., where `encl` gets `parent.env(environment())`. Implementing 2) amounts to replacing `.init_call` in [memoise.R](https://github.com/hadley/memoise/blob/master/R/memoise.R#L137) with `` eval.parent(`[[<-`(match.call(), 1L, encl$`_f`)) ``.

I have implement such fixes in commits [018ef0a](https://github.com/egnha/memoise/commit/018ef0a91f5d740282da47df2043625e398c0828), [7a46d42](https://github.com/egnha/memoise/commit/7a46d420b3978feba1d1c55f03f3de71e2b262b8), [e32fb1b](https://github.com/egnha/memoise/commit/e32fb1b1dc0028df18dd43d02a699c35f2779505). `memoise()` is even a bit simpler, now, because `bquote()`'ing is no longer necessary. All existing tests pass, in addition to a [test that verifies the absence of name clashes](https://github.com/egnha/memoise/blob/fix-name-clash/tests/testthat/test-memoise.R#L236-L286).

With such changes, argument names won't be hijacked by internal names:
```R
memoise(function(hash) hash)("OK!")
#> [1] "OK!"
```

**Comment by jimhester** [comment]
Thanks, this is now fixed, see https://github.com/hadley/memoise/commit/b0da939346d3e3c16291bcff8723f2fcc63a966d and your previous commits.

**Comment by egnha** [comment]
Thanks for the merge and for fixing the test (7bd7b75b528752efade738620b34c91ff470d910).
