### ISSUE TITLE
Memoise does not cache by environments (only by arguments)

### ISSUE THREAD

**Issue by peterhurford** [hadley/memoise#8]
```R
> fn <- function(x) x + y
> environment(fn)$y <- 1
> fn2 <- memoise::memoise(fn)
> fn2(1)
[1] 2
> environment(fn)$y <- 2
> fn2(1)
[1] 2
```

**Comment by peterhurford** [comment]
This is related to #6, but a different case.

**Comment by jimhester** [comment]
This is true. Do you have an example where this distinction matters in practice? This does not seem like a use case we should be worrying about IMHO. Modifying function environments post-definition is not exactly standard practice.

**Comment by peterhurford** [comment]
Fair enough.
