### ISSUE TITLE
Not working with paste functions

### ISSUE THREAD

**Issue by lucacerone** [hadley/memoise#9]
I got the following issue when using the memoise  function on `paste`:

    library(memoise)
    p <- memoise(paste)
    
    p("luca")
    Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
    Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?

**Comment by krlmlr** [comment]
Works for me (Ubuntu 15.04, R 3.2.2, GitHub version).

**Comment by jimhester** [comment]
Works for me as well. @lucacerone if you are able to provide a reproducible example please reopen this issue.
